### PR TITLE
Test gradle and maven

### PR DESCRIPTION
**Pull request by ignasi35**
References #34 

(keeping it draft for a bit, I need to split the `script` into separate travis jobs.

### CODE REVIEW

**Comment by ignasi35** [comment]
The build failed because of #36. Once #37 is merged, the build should pass.

I'll close/Reopen the PR to trigger a new build.

**Comment by ignasi35** [comment]
Another improvement on the travis job definitions is to run the test for different values of the properties. E.g.:

```
  - sbt new file://$PWD \
     --name=hello-world-grpc \
     --scala_major_version=2.12 \
     --scala_version=2.12.11 \
     --force && pushd...
```

**Comment by raboof** [comment]
Gradle is failing with:
```
Task :generateProto FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':generateProto'.
> Could not resolve all files for configuration ':protobufToolsLocator_akkaGrpc'.
   > Could not find akka-grpc-codegen_2.12-assembly.jar (com.lightbend.akka.grpc:akka-grpc-codegen_2.12:0.8.4).
     Searched in the following locations:
         file:/home/travis/.m2/repository/com/lightbend/akka/grpc/akka-grpc-codegen_2.12/0.8.4/akka-grpc-codegen_2.12-0.8.4-assembly.jar
```
weird, I can't reproduce that :(

**Comment by ignasi35** [comment]
> weird, I can't reproduce that :(

Was your local project built before or after #27 was merged?

**Comment by raboof** [comment]
> Was your local project built before or after #27 was merged?

Ah, somehow I though this PR was already rebased, but obviously not. just did.

**Comment by raboof** [comment]
After rebasing it still doesn't seem to look at maven central to get this resource - weird!

**Comment by ignasi35** [comment]
I've dropped the travisCI cache for the `master` branch which was 5 days old in case that was interfering.

**Comment by raboof** [comment]
Awesome, thanks!

**Pull request merged**
